### ISSUE TITLE
Is it possible that it could work in visual studio code?

### ISSUE THREAD

**Issue by runtimevic** [philippleidig/TwinCAT.ProductivityTools#2]
Hello,
I think it would be a good idea if it could work in visual studio code,
can you create a new project but for visual studio code?
and that it had the functionality of being able to transfer a pou to the plc from visual stuido code?

**Comment by philippleidig** [comment]
Hi, unfortunately this is not possible as VS Code uses a different API for 
extensibility and is not developed against the .NET Framework.
